# base url = http://localhost:3001/api/

# GET     http://localhost:3001/api/users/1
# DELETE  http://localhost:3001/api/users/8

# POST    http://localhost:3001/api/users
# Content-Type: application/json

# {
#     "username": "Lernantino",
#     "email": "lernantino@gmail.com",
#     "password": "password1234"
# }

# POST http://localhost:3001/api/posts/
# Content-Type: application/json

# {
#   "title": "Runbuddy reaches 1 million subscribers",
#   "post_url": "https://runbuddy.com/press",
#   "user_id": 1
# }

# PUT http://localhost:3001/api/posts/upvote
# Content-Type: application/json

# {
#     "user_id": 1,
#     "post_id": 1
# }