# base url = http://localhost:3001/api/

# GET     http://localhost:3001/api/users/9
# DELETE  http://localhost:3001/api/users/8

POST    http://localhost:3001/api/users/login
Content-Type: application/json

{
    "email": "wally@email.com",
    "password":"newpassword"
}