# base url = http://localhost:3001/api/

GET     http://localhost:3001/api/users
# DELETE  http://localhost:3001/api/users/8

# POST    http://localhost:3001/api/users
# Content-Type: application/json

{
    "username": "",
    "email":"bob4@email.com",
    "password":"password"
}